# Funding options for this project
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [bybren-llc]
custom: ["https://github.com/bybren-llc/wtfb-projects-template/blob/main/SPONSOR.md"]
